# Generated by Django 5.0 on 2023-12-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('weight', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(upload_to='burgers')),
            ],
            options={
                'verbose_name': 'Бургер',
                'verbose_name_plural': 'Бургеры',
            },
        ),
    ]
